### PR TITLE
Remove `allowed_values` from edition

### PR DESCRIPTION
**Pull request by benilovj**
The mappings used to be used in "policy-publisher", but that app
has been since changed (https://github.com/alphagov/policy-publisher/pull/106).

Now they are [no longer used anywhere](https://github.com/search?q=user%3Aalphagov+detailed_format&type=Code&utf8=%E2%9C%93), `display_type` carries the same
information and can be used instead.

/cc @rboulton @tijmenb 

**This shouldn't be merged until https://github.com/alphagov/policy-publisher/pull/106 has been deployed.**

### CODE REVIEW

**Comment by tijmenb** [comment]
:+1: but we should hold off until policy-publisher is deployed right?

**Comment by rboulton** [comment]
This looks fine, but please don't merge this until policy-publisher is deployed.

**Comment by benilovj** [comment]
> This looks fine, but please don't merge this until policy-publisher is deployed.

Yes, sorry, I've changed the title on this PR and I've got a deploy slot for this afternoon for Policy Publisher.

**Comment by rboulton** [comment]
I think pp is deployed now, so this can be merged?

**Comment by benilovj** [comment]
Yes, PP is out, this is ready to be merged.

**Pull request merged**
