### PR TITLE
Make Taxon pages indexable by govuk-index

### PR DESCRIPTION
**Pull request by elenatanasoiu**
For: https://trello.com/c/M5sF6vyc/93-2-renamed-worldwide-taxonomy-pages-not-showing-correctly-in-search

## Why
Following on the work done previously to rename a certain subset of taxons ("world location") from `<location name> and the UK` to `UK help and services in <location name>`, we discovered that after republishing them they do not show up in search results https://www.gov.uk/api/search.json?filter_link=/world/spain. That's because taxons have not been migrated to be indexed using the `govuk-index` in rummager. 

We're now publishing taxons from `content-tagger` directly to `publishing-api`, which is not automatically picked up by rummager and indexed accordingly. 

## What
Finishes the migration of taxon pages by adding the last remaining bit: making them indexable in the govuk-index.

There are docs in rummager for doing this type of migration: https://github.com/alphagov/rummager/blob/master/doc/new-indexing-process.md

We also have these previous migration PRs as a starting point:
https://github.com/alphagov/rummager/pull/1114
https://github.com/alphagov/rummager/pull/1014
https://github.com/alphagov/rummager/pull/1077

However, these three PRs were slightly different because they had extra fields that meant rummager had to be adjusted to include these special fields when returning results.

For taxons, we're settling for just the basic fields returned for an edition. In order to see what representation publishing-api has of taxons, as well as for a type of edition (`aaib_report`) we used a rake task to give us a preview of the document structure.

Rake task is here: https://github.com/alphagov/publishing-api/blob/master/lib/tasks/queue.rake#L51

Previews for
- taxon: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/263/consoleFull
- aaib_report: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/266/console
- external_content: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/265/console

### CODE REVIEW

**Review by tijmenb — DISMISSED** [review]
This needs some coordination with the nav/taxonomy team.

The world pages are different from other taxons (like https://www.gov.uk/education/student-grants-bursaries-scholarships). As far as I know we've previously intentionally excluded them from internal search.

What's more, since last week a couple of thousand new taxons have been published in an "alpha" state. Those we explicitly exclude from Google (https://github.com/alphagov/collections/pull/507), and definitely don't want to show up in internal search.

**Comment by elenatanasoiu** [comment]
I've discussed with the Taxonomy team, who are not intending to add indexing for taxons in the near future, so the search was never expected to offer these world taxons as a result, which was the original purpose of this PR. I'm closing it for now and letting the requester in the Zendesk ticket know this is not a feature that's planned.

**Comment by tijmenb** [comment]
We have a solution (and the taxonomy team is okay with this). 

@MatMoore explained that we can selectively index the taxons by adding a [whitelist like the one that exists for special_routes](https://github.com/alphagov/rummager/blob/cf8c3e1435811a0cc1fba5c4833800be0cbce79d/config/govuk_index/migrated_formats.yaml#L52-L54).

From [this list](https://github.com/alphagov/content-tagger/blob/1b06e4e67623b4616d4d75d289cdacb38fb785f1/lib/tasks/taxonomy/update_worldwide_taxon_summary.rake#L6-L231) I gather that it should look like:

```yaml
taxon:
  - /world/afghanistan
  - /world/albania
  - /world/algeria
  - /world/angola
  - /world/anguilla
  - /world/argentina
  - /world/armenia
  - /world/australia
  - /world/austria
  - /world/azerbaijan
  - /world/bahrain
  - /world/bangladesh
  - /world/barbados
  - /world/belarus
  - /world/belgium
  - /world/belize
  - /world/bolivia
  - /world/bosnia-and-herzegovina
  - /world/botswana
  - /world/brazil
  - /world/british-antarctic-territory
  - /world/british-virgin-islands
  - /world/brunei
  - /world/bulgaria
  - /world/burma
  - /world/cambodia
  - /world/cameroon
  - /world/canada
  - /world/cayman-islands
  - /world/chile
  - /world/china
  - /world/colombia
  - /world/costa-rica
  - /world/croatia
  - /world/cuba
  - /world/cyprus
  - /world/czech-republic
  - /world/democratic-republic-of-the-congo
  - /world/denmark
  - /world/dominican-republic
  - /world/ecuador
  - /world/egypt
  - /world/eritrea
  - /world/estonia
  - /world/ethiopia
  - /world/fiji
  - /world/finland
  - /world/france
  - /world/gambia
  - /world/georgia
  - /world/germany
  - /world/ghana
  - /world/greece
  - /world/guatemala
  - /world/guyana
  - /world/holy-see
  - /world/honduras
  - /world/hong-kong
  - /world/hungary
  - /world/iceland
  - /world/india
  - /world/indonesia
  - /world/iran
  - /world/iraq
  - /world/ireland
  - /world/israel
  - /world/italy
  - /world/jamaica
  - /world/japan
  - /world/jordan
  - /world/kazakhstan
  - /world/kenya
  - /world/kosovo
  - /world/kuwait
  - /world/laos
  - /world/latvia
  - /world/lebanon
  - /world/libya
  - /world/lithuania
  - /world/luxembourg
  - /world/macedonia
  - /world/madagascar
  - /world/malawi
  - /world/malaysia
  - /world/maldives
  - /world/mali
  - /world/malta
  - /world/mauritius
  - /world/mexico
  - /world/moldova
  - /world/mongolia
  - /world/montenegro
  - /world/montserrat
  - /world/morocco
  - /world/mozambique
  - /world/namibia
  - /world/nepal
  - /world/netherlands
  - /world/new-zealand
  - /world/nigeria
  - /world/north-korea
  - /world/norway
  - /world/oman
  - /world/pakistan
  - /world/panama
  - /world/papua-new-guinea
  - /world/peru
  - /world/philippines
  - /world/poland
  - /world/portugal
  - /world/qatar
  - /world/romania
  - /world/russia
  - /world/rwanda
  - /world/saudi-arabia
  - /world/senegal
  - /world/serbia
  - /world/seychelles
  - /world/sierra-leone
  - /world/singapore
  - /world/slovakia
  - /world/slovenia
  - /world/solomon-islands
  - /world/somalia
  - /world/south-africa
  - /world/south-korea
  - /world/south-sudan
  - /world/spain
  - /world/sri-lanka
  - /world/sudan
  - /world/sweden
  - /world/switzerland
  - /world/syria
  - /world/taiwan
  - /world/tajikistan
  - /world/tanzania
  - /world/thailand
  - /world/timor-leste
  - /world/trinidad-and-tobago
  - /world/tunisia
  - /world/turkey
  - /world/turkmenistan
  - /world/turks-and-caicos-islands
  - /world/uganda
  - /world/ukraine
  - /world/united-arab-emirates
  - /world/uruguay
  - /world/usa
  - /world/uzbekistan
  - /world/venezuela
  - /world/vietnam
  - /world/yemen
  - /world/zambia
  - /world/zimbabwe
  - /world/andorra
  - /world/antigua-and-barbuda
  - /world/bahamas
  - /world/benin
  - /world/bhutan
  - /world/burkina-faso
  - /world/cape-verde
  - /world/comoros
  - /world/congo
  - /world/cote-d-ivoire
  - /world/djibouti
  - /world/dominica
  - /world/equatorial-guinea
  - /world/grenada
  - /world/guinea-bissau
  - /world/haiti
  - /world/kiribati
  - /world/lesotho
  - /world/liberia
  - /world/liechtenstein
  - /world/macao
  - /world/marshall-islands
  - /world/micronesia
  - /world/nauru
  - /world/nicaragua
  - /world/niger
  - /world/the-occupied-palestinian-territories
  - /world/palau
  - /world/paraguay
  - /world/samoa
  - /world/sao-tome-and-principe
  - /world/st-kitts-and-nevis
  - /world/st-vincent-and-the-grenadines
  - /world/suriname
  - /world/swaziland
  - /world/togo
  - /world/tuvalu
  - /world/vanuatu
  - /world/bermuda
  - /world/burundi
  - /world/el-salvador
  - /world/falkland-islands
  - /world/guinea
  - /world/st-helena-ascension-and-tristan-da-cunha
  - /world/st-lucia
  - /world/kyrgyzstan
  - /world/pitcairn-island
  - /world/chad
  - /world/mauritania
  - /world/american-samoa
  - /world/aruba
  - /world/bonaire-st-eustatius-saba
  - /world/central-african-republic
  - /world/curacao
  - /world/french-guiana
  - /world/french-polynesia
  - /world/gabon
  - /world/gibraltar
  - /world/guadeloupe
  - /world/martinique
  - /world/mayotte
  - /world/monaco
  - /world/new-caledonia
  - /world/reunion
  - /world/san-marino
  - /world/south-georgia-and-south-sandwich-islands
  - /world/st-maarten
  - /world/st-pierre-and-miquelon
  - /world/tonga
  - /world/wallis-and-futuna
  - /world/western-sahara
  - /world/st-martin
```

**Comment by cbaines** [comment]
> We have a solution (and the taxonomy team is okay with this).
> 
> @MatMoore explained that we can selectively index the taxons by adding a whitelist like the one that exists for special_routes.

Interesting, this sounds ok to me. The other option I was considering suggesting was somehow getting Content Tagger to update the titles of the search items (for the non-existent world location pages) in Rummager when it publishes the taxons, but this seems a bit neater than that.

I'm also guessing that the content sent by the Publishing API for the taxons will somehow replace or supersede the old content in Rummager for the now non-existent world location pages?

**Review by cbaines — DISMISSED** [review]
I don't have a lot of context on the internals of Rummager, but this looks of to me.

**Comment by MatMoore** [comment]
Yup I think @tijmenb's change will work, if the intent is to completely exclude regular topic pages from search. This should be revisited at some point because topic pages are important and should be findable.

If we get to the point where we're happy indexing all live taxons we could revert back to @elenatanasoiu's commit and just add in some code to ignore anything with `document_type` = `taxon` and `phase` != `live`.

**Comment by tijmenb** [comment]
(Note that I didn't actually make a change to this PR, just the comment)

**Comment by elenatanasoiu** [comment]
@tijmenb @cbaines Is this still something Taxonomy wants?

**Comment by cbaines** [comment]
> @tijmenb @cbaines Is this still something Taxonomy wants?

The approach that Tijmen suggested won't impact the Taxonomy teams work. In terms of "wants" from a product perspective, I don't think the Worldwide pages are within the scope of the Taxonomy teams work.

**Review by thomasleese — APPROVED** [review]
I don't have too much context on this, but based on the description in the PR and the Trello card it makes sense!

**Review by bevanloon — APPROVED** [review]
@tijmenb be good if you cast your eye over this as well please

**Review by tijmenb — APPROVED** [review]
Seems legit!

**Pull request merged**
