### PR TITLE
Remove all code related to indexing taxonomy mappings

### PR DESCRIPTION
**Pull request by malcolmbaig**
This was a spike to get taxonomy data into the search API. This approach
has since been superseded by the creation of dedicated taxon content
items that are tagged via the links hash.

### CODE REVIEW

**Comment by tijmenb** [comment]
Sorry - my govuk-lint PR will probably cause some conflicts here.

**Comment by benlovell** [comment]
The tectonic plates just shifted.

**Comment by malcolmbaig** [comment]
Back in the game.

**Pull request merged**
