### PR TITLE
[DO NOT MERGE] Use elasticsearch 5 (breaks elasticsearch 2 compatibility!)

### PR DESCRIPTION
**Pull request by barrucadu**
**Moved to https://github.com/alphagov/search-api/pull/2**

**CI currently failing because it's trying to test against elasticsearch 2**

---

Updates rummager to use elasticsearch 5, dropping elasticsearch 2 compatibility, whilst preserving the externally visible API.

### Known to be working:

- **search features:**
  - externally exposed query format (if all the reading apps work, this is fine)
- **apps which read from rummager:**
  - **collections:**
    - browse page ([example](http://collections.dev.gov.uk/browse))
    - organisation index pages ([example](http://collections.dev.gov.uk/government/organisations))
    - organisation pages ([example (skip_slimmer because there appears to be an html error in the template)](http://collections.dev.gov.uk/government/organisations/cabinet-office?skip_slimmer=1))
    - services and information pages ([example](http://collections.dev.gov.uk/government/organisations/hm-revenue-customs/services-information))
    - subtopic pages ([example](http://collections.dev.gov.uk/topic/oil-and-gas/infrastructure-and-decommissioning))
    - taxonomy pages ([example](http://collections.dev.gov.uk/education))
    - topic pages ([example](http://collections.dev.gov.uk/topic/oil-and-gas))
    - worldwide taxonomy pages ([example](http://collections.dev.gov.uk/world/japan))
  - **content-tagger:**
    - organisation tagging progress for projects ([example](http://content-tagger.dev.gov.uk/projects?progress_for_organisations=department-for-transport%2C+high-speed-two-limited))
    - `ContentExport` / `TaggedContentExporter` - I don't think this is used anywhere
    - `rake content:tagged_to_ancestor`
    - `rake govuk:export_content_by_organisations` (example parameters: `[uk-border-agency,border-force]`)
    - `rake govuk:export_mainstream_taxons`
    - `rake metrics:taxonomy:record_content_coverage_metrics` tested by printing results to stdout
    - `rake taxonomy:health_checks`
  - **finder-frontend:**
    - finders:
      - filtering by facets ([example](http://finder-frontend.dev.gov.uk/aaib-reports?keywords=&aircraft_category%5B%5D=commercial-fixed-wing&report_type%5B%5D=correspondence-investigation&date_of_occurrence%5Bfrom%5D=&date_of_occurrence%5Bto%5D=))
      - filtering by text ([example](http://finder-frontend.dev.gov.uk/aaib-reports?keywords=%22A320-214%22&date_of_occurrence%5Bfrom%5D=&date_of_occurrence%5Bto%5D=))
      - filtering by date ([example](http://finder-frontend.dev.gov.uk/aaib-reports?keywords=&date_of_occurrence%5Bfrom%5D=&date_of_occurrence%5Bto%5D=2000))
    - search:
      - searching by text ([example](http://finder-frontend.dev.gov.uk/search?q=micropig))
      - filtering by organisation ([example](http://finder-frontend.dev.gov.uk/search?q=frog&filter_organisations%5B%5D=home-office))
  - **hmrc-manuals-api:**
    - `rake redirect_all_hmrc_sections_to_parent_manual` (example parameters: `[oil-taxation-manual]`)
    - `rake remove_hmrc_manuals` (example parameters: `[employee-tax-advantaged-share-scheme-user-manual]`)
  - **licence-finder**
    - fetching licences ([example](http://licencefinder.dev.gov.uk/licence-finder/licences?activities=183&location=england&sectors=3))
  - **search-admin:**
    - "similar to" searches ([example](http://search-admin.dev.gov.uk/similar-search-results/result?utf8=%E2%9C%93&base_path=%2Fguidance%2Fpupil-premium-reviews&commit=Show+similar+search+results))
  - **rummager:**
    - `rake analytics:create_data_import_csv` (example parameters: `[out]`)
    - `rake debug:show_govuk_link` (example parameters: `[/aaib-reports/aaib-investigation-to-emb-145ep-g-ckag]`)
    - `rake debug:show_new_synonyms` (example parameters: `[brexit]`)
    - `rake debug:show_old_index_link` (example parameters: `[/government/publications/desider-2019]`)
    - `rake report_inconsistent_facet_values` (this doesn't work in integration!)
    - `rake report_inconsistent_aggregate_values`
    - `rake rummager:check_for_non_draft_taxons` (example parameters: `[aaib_report,govuk]` and `[aaib-report,govuk]` (an invalid format name))
    - `rake rummager:check_recovery` (example parameters: `[govuk-2019-01-21t14:55:49z-0cd70c95-49f2-4e3b-b7b6-0e7ff07f2525]` (has to match your index name)
    - `rake rummager:list_indices` (example parameters: `RUMMAGER_INDEX=all`)
    - `rake rummager:monitor_indices`
    - `rake sitemap:generate_and_replace`
  - **whitehall:**
    - filtered latest documents ([example](http://whitehall-frontend.dev.gov.uk/government/latest?departments[]=department-for-education))
    - announcements finder ([example](http://whitehall-frontend.dev.gov.uk/government/announcements))
    - publications controller ([example](http://whitehall-frontend.dev.gov.uk/government/publications))
    - statistics announcements finder ([example](http://whitehall-frontend.dev.gov.uk/government/statistics/announcements))
    - topical events finder ([example (migrated to finder-frontend)](http://finder-frontend.dev.gov.uk/government/topical-events))
    - world location api ([example](http://whitehall-frontend.dev.gov.uk/api/world-locations))
    - world location news finder ([example](http://whitehall-frontend.dev.gov.uk/government/world-location-news))
- **apps which write to rummager:**
  - **rummager:**
    - `rake delete:all_duplicates` (directly calls something covered by the testsuite)
    - `rake delete:by_format` (example parameters: `[aaib_report,govuk]`)
    - `rake delete:duplicates` (directly calls something covered by the testsuite)
    - `rake destroy_metadata_for_base_paths` (example parameters: `[/government/publications/trade-marks-and-designs-if-theres-no-brexit-deal]`)
    - `rake destroy_metadata_for_eu_exit_guidance`
    - `rake populate_metadata` (directly calls something covered by the testsuite)
    - `rake rummager:clean` (example parameters: `RUMMAGER_INDEX=all` - do this after creating new indices)
    - `rake rummager:create_index` (example parameters: `[detailed]` - check the new inde has been created in elasticsearch-head)
    - `rake rummager:create_all_indices` (example parameters: `RUMMAGER_INDEX=detailed`)
    - `rake rummager:lock` (example parameters: `RUMMAGER_INDEX=all` - look for `blocks` in index metadata)
    - `rake rummager:migrate_schema` (example parameters: `RUMMAGER_INDEX=govuk CONFIRM_INDEX_MIGRATION_START=1`)
    - `rake rummager:sync_govuk` (example parameters: `RUMMAGER_INDEX=metasearch` - check the doc count in elasticsearch-head)
    - `rake rummager:switch_to_empty_index` (example parameters: `RUMMAGER_INDEX=metasearch`)
    - `rake rummager:switch_to_named_index` (do this after `switch_to_empty_index`. example parameters: `[govuk-2019-01-21t14:55:49z-0cd70c95-49f2-4e3b-b7b6-0e7ff07f2525] RUMMAGER_INDEX=govuk` (your old index name) - try the cma-cases finder again)
    - `rake tag_metadata` (need to download the csv from govuk-app-deployment-secrets)
    - `rake rummager:unlock` (example parameters: `RUMMAGER_INDEX=all` - look for `blocks` in index metadata)
    - documents API (tested by whitehall)
    - rabbitmq queue worker (tested by publishing-api / specialist-publisher)
  - **search-admin:**
    - `rake travel_advice:import_best_bets` (example parameters: `[travel-advice.csv,"Richard Boulton"]` with travel-advice.csv being `kenya,/world/organisations/british-high-commission-nairobi`)
    - create a query
    - destroy a query
    - create a bet
    - update a bet
    - destroy a bet
  - **whitehall**
    - publishing a new edition
    - withdrawing an edition
- **other:**
  - gds-api-adapters (if all the apps work this is fine)

### Changes

- **similarity scoring for text queries:** elasticsearch 5 has changed the default similarity scoring metric to BM25, which behaves differently to the old one.  The old one is being phased out in [Lucene](https://issues.apache.org/jira/browse/LUCENE-7347), so we have no choice but to switch.

### Might be working:

- **best/worst bets:** I've tried a few best bets and they seem to be working, but worst bets seem to be broken both on this branch and on master.  eg, `/vehicle-tax` is a worst bet for "apply for benefits", yet it still (incorrectly) shows up in the search results: https://www.gov.uk/search?q=apply+for+benefits&filter_organisations%5B%5D=driver-and-vehicle-licensing-agency
- **rummager's `rake rummager:update_popularity`** trying to run this locally overloaded my dockerised elasticsearch instance, but the actual logic is covered by the testsuite.
- **search items from publicapi:** search items in es5 include empty arrays which which seemed to get stripped out with es2 (https://gist.github.com/barrucadu/290facb999c3caf24f02d8f666162a31).  These extra fields are in the schema for the type, so it's not returning anything *wrong*, but we might want to restore the old behaviour, which may not be as simple as unconditionally stripping empty fields.
- **whitehall's statistics controller** ([example](http://whitehall-frontend.dev.gov.uk/government/statistics?keywords=&taxons%5B%5D=495afdb6-47be-4df1-8b38-91c8adb1eefc&departments%5B%5D=all&from_date=&to_date=)) gives error about duplicate publications on [/government/statistics](http://whitehall-frontend.dev.gov.uk//government/statistics) with both rummager-es2 and rummager-es5 (in the dev VM), unless query parameters are given.

### Known to be broken:

- **rummager's `rake rummager:compare_govuk`:** this is broken in staging/integration too, as it tries to compare against the `mainstream` index, which doesn't exist.
- **search-admin updating queries:** broken for non-rummager reasons, Platform Health have a card.
- **search-admin `rake reindex_best_bets`:** broken for non-rummager reasons, Platform Health have a card.

### To check:

- **other:**
  - env-sync-and-backup
  - publishing-e2e-tests

## How to use this

1. Set up a local elasticsearch 5
2. Change the port rummager connects to (if it's not listening on 9200)
3. Create the indices
4. Import data with Kat's script

```diff
diff --git a/elasticsearch.yml b/elasticsearch.yml
index 67b1b33c..200bd4df 100644
--- a/elasticsearch.yml
+++ b/elasticsearch.yml
@@ -1,5 +1,5 @@
 production: &default
-  base_uri: <%= ENV["ELASTICSEARCH_URI"] || 'http://localhost:9200' %>
+  base_uri: <%= ENV["ELASTICSEARCH_URI"] || 'http://localhost:9205' %>
   content_index_names: ["detailed", "government"]
   govuk_index_name: "govuk"
   auxiliary_index_names: ["page-traffic", "metasearch"]
```

---

Trello card: [Make rummager able to query es5](https://trello.com/c/q5WUhqbt/12-make-rummager-able-to-query-es5)
Trello card: Make rummager able to update es5

### CODE REVIEW

**Comment by barrucadu** [comment]
The new similarity metric is [BM25](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/index-modules-similarity.html#bm25):

> TF/IDF based similarity that has built-in tf normalization and is supposed to work better for short fields (like names). See [Okapi_BM25](https://en.wikipedia.org/wiki/Okapi_BM25) for more details.

**elasticsearch 2**
es2

**elasticsearch 5**
es5

**Comment by brucebolt** [comment]
Looks good, nice documentation in the PR.  I notice the Jenkins build is failing.  Also, I'm wondering if this would be better raised against `search-api`?

**Comment by barrucadu** [comment]
Jenkins is failing because it's trying to test against elasticsearch 2.  I've put a card in the backlog for figuring out how to get elasticsearch 5 available there.

**Comment by barrucadu** [comment]
Moved to https://github.com/alphagov/search-api/pull/2

**Pull request closed without merging**
