### PR TITLE
Allow per-cluster search config and use new text similarity for es6

### PR DESCRIPTION
**Pull request by barrucadu**
```
$ ELASTICSEARCH_A_URI='http://localhost:9200' ELASTICSEARCH_B_URI='http://localhost:9201' bundle exec rake search:create_all_indices SEARCH_INDEX=all
...
$ curl localhost:9200/govuk/_settings 2>/dev/null | json_pp | grep -C5 similarity
               "total_fields" : {
                  "limit" : "2000"
               }
            },
            "number_of_replicas" : "1",
            "similarity" : {
               "default" : {
                  "type" : "classic"
               }
            },
            "number_of_shards" : "3"
$ curl localhost:9201/govuk/_settings 2>/dev/null | json_pp | grep -C5 similarity
$
```

---

[Trello card](https://trello.com/c/MX1MtsEf/717-switch-to-new-elasticsearch-text-similarity-metric-%F0%9F%8D%90-l)

### CODE REVIEW

**Review by bilbof — APPROVED** [review]

**Comment by bilbof** [comment]
Is there a way to test the clusters have different schemas applied?

**Comment by barrucadu** [comment]
I'm not sure, I can't see an obvious way.

**Comment by bilbof** [comment]
I suppose in an integration test, you could instantiate all clusters, then use the ES client to inspect the settings and check they're what they should be?

**Comment by barrucadu** [comment]
That's a bit tricky because we don't set the *entire* config, so the result of `curl localhost:9200/govuk/_settings` isn't the same as what we have in our yaml file.

We could check the yaml file is a subset of the ES-reported index config, but that wouldn't help in this case where we want to check that removing a key from the config file worked.

**Pull request merged**
