### PR TITLE
Bump GDS API adapters to 20.1.1

### PR DESCRIPTION
**Pull request by elliotcm**
This changes the user agent to include the app
name in API requests.

https://trello.com/c/qkHdtob4/247-bump-gds-api-adapters-everywhere-it-s-used-to-include-user-agent-information

### CODE REVIEW

**Comment by alext** [comment]
In light of the changes to the router-api client (#162), we should probably remove the `:skip_commit => true` param from the router calls in `lib/tasks/router.rake`.

**Comment by elliotcm** [comment]
@alext Is that the PR you meant to reference?

**Comment by alext** [comment]
Doh, no, that's the PR number on gds-api-adapters.  I meant https://github.com/alphagov/gds-api-adapters/pull/162

**Comment by elliotcm** [comment]
@alext thanks for the note, updated.

**Pull request merged**
