### PR TITLE
Add assurance technique approach to AI assurance portfolio technique elasticsearch type

### PR DESCRIPTION
**Pull request by ryanb-gds**
Required as part of addition of new assurance technique approach facet to AI Assurance technique specialist finder

Trello: https://trello.com/c/dk6wY8nD
Zendesk: https://govuk.zendesk.com/agent/tickets/5444446

### CODE REVIEW

**Comment by ryanb-gds** [comment]
~~Blocked pending merge of https://github.com/alphagov/publishing-api/pull/2479~~

**Review by Rosa-Fox — APPROVED** [review]
Hi, I compared this to the [PR in which the Assurance Techniques finder was added](https://github.com/alphagov/search-api/commit/dc6459c72f24b0979b0a4c5e9fcef2cbc0cbf8ca) and the [docs](https://github.com/alphagov/search-api/blob/main/docs/adding-new-fields.md) and think it looks good. However I have not run it. Have you tested on integration?

**Comment by ryanb-gds** [comment]
> Hi, I compared this to the [PR in which the Assurance Techniques finder was added](https://github.com/alphagov/search-api/commit/dc6459c72f24b0979b0a4c5e9fcef2cbc0cbf8ca) and the [docs](https://github.com/alphagov/search-api/blob/main/docs/adding-new-fields.md) and think it looks good. However I have not run it. Have you tested on integration?

Not yet, I will give it a try once the specialist publisher PR is ready

**Comment by ryanb-gds** [comment]
Screenshot 2023-08-30 at 10 06 51
Successful test

**Pull request merged**
