### PR TITLE
Add links based business finder

### PR DESCRIPTION
**Pull request by peteglondon**
We want to test the new structure for the business finder.

The PR adds a yaml file with the new structure so we can deploy and test it in integration.

### CODE REVIEW

**Comment by peteglondon** [comment]
[Mapping Rummager request/response in Finder Frontend](https://trello.com/c/Sd7omEFH/263-mapping-rummager-request-response-in-finder-frontend)

**Comment by peteglondon** [comment]
[Mapping Rummager request/response in Finder Frontend](https://trello.com/c/Sd7omEFH/263-mapping-rummager-request-response-in-finder-frontend)

**Comment by peteglondon** [comment]
[Mapping Rummager request/response in Finder Frontend](https://trello.com/c/Sd7omEFH/263-mapping-rummager-request-response-in-finder-frontend)

**Review by steventux — COMMENTED** [review]
Are you planning to merge then revert this once complete? Not quite sure of the intention of this PR. It's possible to deploy this branch to integration and publish the finder, alternatively link the real finder on integration to the facet group. I don't quite understand the advantage of merging this.

**Comment by peteglondon** [comment]
Need to do this in `search-api` now

**Pull request closed without merging**
