### PR TITLE
Kill off advanced search

### PR DESCRIPTION
**Pull request by barrucadu**
This is only used by whitehall.  whitehall#5122 switches to the normal
search endpoint, so advanced search can be removed.

Before this commit is merged, the endpoint should be removed from
gds-api-adapters.

---

[Trello card](https://trello.com/c/kWUWnvcz/1120-spike-kill-off-search-apis-advanced-search-endpoint)

### CODE REVIEW

**Review by bilbof — APPROVED** [review]
Amazing ✨ ➖💯

**Review by hannako — COMMENTED** [review]
Do these files need deleting too?

https://github.com/alphagov/search-api/blob/master/config/finders/advanced-search.yml
https://github.com/alphagov/search-api/blob/master/doc/advanced-search.md
https://github.com/alphagov/search-api/blob/master/lib/search/result_set.rb


Amending here:
https://github.com/alphagov/search-api/blob/93cd40cb4c9503c283c144baaf69404044a94c63/lib/search/presenters/result_presenter.rb#L81
https://github.com/alphagov/search-api/blob/master/doc/publishing-finders.md#L6
https://github.com/alphagov/search-api/blob/master/README.md#145
https://github.com/alphagov/search-api/blob/93cd40cb4c9503c283c144baaf69404044a94c63/spec/unit/publishing_api_finder_publisher_spec.rb#L5

**Comment by barrucadu** [comment]
The `/search/advanced` finder is unrelated to the advanced search endpoint - we just have a lot of things called "advanced search" 😢

**Comment by hannako** [comment]
Oh god. Confusing!!!

**Pull request merged**
