### PR TITLE
Set cache headers on sitemaps

### PR DESCRIPTION
**Pull request by barrucadu**
These are the headers nginx used for the files on disk: https://github.com/alphagov/govuk-puppet/pull/9628/files

### CODE REVIEW

**Review by sihugh — APPROVED** [review]

**Review by sihugh — CHANGES_REQUESTED** [review]
The RFC says:
> MUST be in RFC 1123 date format

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
Example from linked page:
`Expires: Thu, 01 Dec 1994 16:00:00 GMT`

**Review by sihugh — APPROVED** [review]

**Comment by sihugh** [comment]
📅 🚀 🎸

**Comment by barrucadu** [comment]
It's occurred to me that there's a race condition here, as the sitemaps are generated after midnight - you could get yesterday's sitemaps cached for a day if you request them in that window.  But is having a day old sitemap a problem?  *Probably* not.

**Comment by sihugh** [comment]
Some of our pages haven't been indexed by Google for months, and not every page is in the sitemap anyway (for example chapters in guides), so I think it's fine

**Pull request merged**
