### PR TITLE
Retry on failure when multiple ES hosts

### PR DESCRIPTION
**Pull request by dwhenry**
This will allow us to move away from the ES proxy

### CODE REVIEW

**Comment by brenetic** [comment]
How come we no longer need to parse the uri's?

**Comment by dwhenry** [comment]
@brenetic we never needed to parse the URI, the gem is happy to receive string values. We want to stop it so that the puppet change I made (reference above) can pass in multiple hosts instead of the localproxy. :)

**Review by MatMoore — COMMENTED** [review]
Are we happy with the default of 3 tries?

This seems reasonable for indexing but not search requests - if a search request takes too long I think it should time out rather than retry, as this could deny service to other users if the service is overloaded.

**Comment by dwhenry** [comment]
@MatMoore updated this so the retry only happens when modifying data, gets should fail immediately.

**Review by MatMoore — APPROVED** [review]

**Pull request merged**
