### PR TITLE
Bump govuk_document_types to 0.1.8

### PR DESCRIPTION
**Pull request by tuzz**

### CODE REVIEW

**Comment by greysteil** [comment]
I think I've asked before but no-one got back to me. Would you be up for automating these dependency update PRs, the same way MoJ do? See https://github.com/ministryofjustice/prison-visits-2/pulls?q=is%3Apr+is%3Aclosed for examples. Hopefully a time-saver, and would mean Dependabot has more data for its compatibility scores, too.

**Comment by tuzz** [comment]
This is probably a question for @boffbowsh, @timblair.

**Comment by boffbowsh** [comment]
Thanks @greysteil. We're currently using Snyk for a similar use case, but are about to re-evaluate that. I'll add Dependabot to the list of things to look at when we do this.

**Review by boffbowsh — APPROVED** [review]

**Comment by dwhenry** [comment]
@tuzz can you rebase this and then we can get it merged.

**Comment by greysteil** [comment]
*Can't resist the urge to mention that Dependabot automatically rebases its PRs for you.* :wink:

**Pull request merged**
